# Generated by Django 5.0.7 on 2024-07-30 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboard',
            name='invited_users',
            field=models.ManyToManyField(related_name='invited_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
