# Generated by Django 5.0.7 on 2024-08-01 17:12

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbanboard',
            name='invited_users',
        ),
        migrations.AddField(
            model_name='kanbanboard',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kanbanboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 8, 1)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 8, 1)),
        ),
    ]
