# Generated by Django 5.0.7 on 2024-08-02 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_kanbanboard_invited_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('todo', 'Todo'), ('in progress', 'in Progress'), ('testing', 'Testing'), ('done', 'Done')], default='todo', max_length=15),
        ),
        migrations.AlterField(
            model_name='kanbanboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 8, 2)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 8, 2)),
        ),
    ]
