# Generated by Django 5.0.7 on 2024-08-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todoitem_category_alter_kanbanboard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'in Progress'), ('testing', 'Testing'), ('done', 'Done')], default='todo', max_length=15),
        ),
    ]
