# Generated by Django 5.0.7 on 2024-08-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_todoitem_description_alter_todoitem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='assigned_users',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='assigned_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
