# Generated by Django 5.0.7 on 2024-08-03 16:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_todoitem_assigned_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'in Progress'), ('testing', 'Testing'), ('done', 'Done')], default='todo', max_length=15),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], default='low', max_length=4),
        ),
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateField(default=datetime.date(2024, 8, 3))),
                ('assigned_users', models.ManyToManyField(related_name='assigned_users', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
