# Generated by Django 5.0.7 on 2024-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_todoitem_assigned_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
