# Generated by Django 5.0.7 on 2024-08-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_todoitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='assigned_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
