# Generated by Django 5.0.7 on 2024-08-04 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_todoitem_assigned_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbanboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 8, 4)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 8, 4)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
