# Generated by Django 5.0.7 on 2024-08-05 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_kanbanboard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbanboard',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 8, 5)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 8, 5)),
        ),
    ]
