# Generated by Django 5.0.7 on 2024-08-07 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_kanbanboard_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_user_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_user_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_user_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_user',
        ),
    ]
