# Generated by Django 5.0.7 on 2024-08-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_contact_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_user_email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_user_phone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_user_name',
            new_name='contact_username',
        ),
    ]
